<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Namgung">

<title>Fuel Efficiency Forensics: A Comparative Regression Analysis of 1974 Automobile Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="gasoline-regression-analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="gasoline-regression-analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="gasoline-regression-analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="gasoline-regression-analysis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="gasoline-regression-analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="gasoline-regression-analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="gasoline-regression-analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="gasoline-regression-analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="gasoline-regression-analysis_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="gasoline-regression-analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="gasoline-regression-analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="gasoline-regression-analysis_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fuel Efficiency Forensics: A Comparative Regression Analysis of 1974 Automobile Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Namgung </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="data-initialization" class="level2">
<h2 class="anchored" data-anchor-id="data-initialization">Data Initialization</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::combine() masks gridExtra::combine()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>file1 <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"https://raw.githubusercontent.com/"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">"mcgillstat/regression/main/data/data-table-B3.csv"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>data_table_B3 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> file1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<section id="regression-modelling-and-significance" class="level3">
<h3 class="anchored" data-anchor-id="regression-modelling-and-significance">Regression Modelling and Significance</h3>
<p>We fit a multiple linear regression model relating gasoline mileage y (miles per gallon) to engine displacement x1 and the number of carburetor barrels x6.</p>
<p>We constructed the analysis-of-variance table, tested for significance of regression and defined appropriate hypotheses for this test.</p>
<p><span class="math display">\[y = \beta_0 + \beta_1 x_1 + \beta_6 x_6 + \epsilon\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> data_table_B3<span class="sc">$</span>y, <span class="co"># $y$ = Miles/gallon</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> data_table_B3<span class="sc">$</span>x1, <span class="co"># $x_1$ = Displacement</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x6 =</span> data_table_B3<span class="sc">$</span>x6 <span class="co"># $x_6$ = Carburetor</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple linear regression model:</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># y = \beta_0 + \beta_1 x1 + \beta_6 x6 + epsilon</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x6, <span class="at">data =</span> dat)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x6, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.0623 -1.6687 -0.3628  1.6221  6.2305 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 32.884551   1.535408  21.417  &lt; 2e-16 ***
x1          -0.053148   0.006137  -8.660 1.55e-09 ***
x6           0.959223   0.670277   1.431    0.163    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.013 on 29 degrees of freedom
Multiple R-squared:  0.7873,    Adjusted R-squared:  0.7726 
F-statistic: 53.67 on 2 and 29 DF,  p-value: 1.79e-10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate ANOVA table</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: y
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
x1         1 955.72  955.72 105.290 3.666e-11 ***
x6         1  18.59   18.59   2.048    0.1631    
Residuals 29 263.23    9.08                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>For the significance of regression, we want to summarize the conclusions via the overall fit, using the F-statistic result from the summary of the overall model.</p>
<p><strong>Hypotheses</strong>:</p>
<p>Neither predictors have any linear relationship with gasoline milage. <span class="math display">\[H_0: \beta_1 = \beta_6 = 0\]</span></p>
<p>At least 1 predictor is useful for predeciting gasoline mileage. <span class="math display">\[H_1: \text{ At least one } \beta_j != 0\]</span></p>
<p><strong>Test Statistic:</strong></p>
<p>“F-statistic: 53.67 on 2 and 29 DF, p-value: 1.79e-10”, from fitting the model, where F = MSR/MSRes = (SSR/(p-1)) / (SSRes)/(n-p)).</p>
<p>F = MSR/MSRes = (974.31/(3-1)) / (263.23)/(32-3)) = approximately 53.65, where p = 3 and n = 32.</p>
<p>Since p-value 1.79e-10 is much smaller than <span class="math inline">\(\alpha\)</span> = 0.05, we reject the null hypothesis <span class="math inline">\(H_0\)</span>.</p>
<p><strong>Interpretation:</strong> There is a statistically significant linear relationship between gasoline mileage (<span class="math inline">\(y\)</span>) and the combination of engine displacement (<span class="math inline">\(x_1\)</span>) and carburetor barrels (<span class="math inline">\(x_6\)</span>).</p>
</section>
<section id="miles-per-gallon-versus-engine-displacement" class="level3">
<h3 class="anchored" data-anchor-id="miles-per-gallon-versus-engine-displacement">Miles per Gallon versus Engine Displacement</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dat, <span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">as.factor</span>(x6)), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"MPG vs. Engine Displacement"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Colored by Number of Carburetors"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Engine Displacement (cu. in.)"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Miles Per Gallon (MPG)"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Carburetors"</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="gasoline-regression-analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="r2-and-adjusted-r2-of-this-model" class="level3">
<h3 class="anchored" data-anchor-id="r2-and-adjusted-r2-of-this-model"><span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> of this model</h3>
<p>Comparing the <span class="math inline">\(R^2\)</span> and adjusted <span class="math inline">\(R^2\)</span> to the simple linear regression model relating to mileage <span class="math inline">\(y\)</span> to engine displacement <span class="math inline">\(x_1\)</span>. This will tell us how well the model explains the data compared to the simpler model.</p>
<p>Recall: <span class="math inline">\(R^2\)</span> is the proportion of variance in the response variable that is predictable from the independent variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract metrics from the Multiple Linear Regression (MLR) model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>r2_mlr <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>r.squared <span class="co"># 0.7872928</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>adj_r2_mlr <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>adj.r.squared <span class="co"># 0.7726233</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Simple Linear Regression model (y ~ x1)</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>model_slr <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> dat)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.7923 -1.9752  0.0044  1.7677  6.8171 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 33.722677   1.443903   23.36  &lt; 2e-16 ***
x1          -0.047360   0.004695  -10.09 3.74e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.065 on 30 degrees of freedom
Multiple R-squared:  0.7723,    Adjusted R-squared:  0.7647 
F-statistic: 101.7 on 1 and 30 DF,  p-value: 3.743e-11</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract metrics from the SLR model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>r2_slr <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_slr)<span class="sc">$</span>r.squared <span class="co"># 0.7722712</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>adj_r2_slr <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_slr)<span class="sc">$</span>adj.r.squared <span class="co"># 0.7646803</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiple Linear Regression Model</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"R-Squared for MLR: "</span>, r2_mlr, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>R-Squared for MLR:  0.7872928 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Adjusted R-Squared for MLR: "</span>, adj_r2_mlr, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adjusted R-Squared for MLR:  0.7726233 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple Linear Regression Model</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"R-Squared for SLR: "</span>, r2_slr, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>R-Squared for SLR:  0.7722712 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Adjusted R-Squared for SLR: "</span>, adj_r2_slr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adjusted R-Squared for SLR:  0.7646803</code></pre>
</div>
</div>
<section id="results" class="level4">
<h4 class="anchored" data-anchor-id="results">Results:</h4>
<p><strong>Multiple Linear Regression (<span class="math inline">\(x_1 + x_6\)</span>) :</strong></p>
<ul>
<li><span class="math inline">\(R^2\)</span> of MLR: 0.7872928</li>
<li>Adjusted <span class="math inline">\(R^2\)</span> of MLR: 0.7726233</li>
</ul>
<p><strong>Simple Linear Regression (<span class="math inline">\(x_1\)</span> only) :</strong></p>
<ul>
<li><span class="math inline">\(R^2\)</span> of SLR: 0.7722712</li>
<li>Adjusted <span class="math inline">\(R^2\)</span> of SLR: 0.7646803</li>
</ul>
<p><span class="math inline">\(R^2\)</span> always increases or stays the same when we add more variables</p>
<p>Coefficient of Determination <span class="math inline">\(R^2\)</span> measures the proportion of variance in the response (<span class="math inline">\(y\)</span>) explained by the predictors. <span class="math inline">\(R^2\)</span> = 1 - <span class="math inline">\(SS_{Res} / SS_{T}\)</span></p>
<p>Adjusted <span class="math inline">\(R^2\)</span> penalizes the model for adding unnecessary predictors.</p>
<p>It accounts for the degrees of freedom (n-p), Adjusted <span class="math inline">\(R^2\)</span> = 1 - <span class="math inline">\((SS_{Res}/(n-p)) / (SS_{T}/(n-1))\)</span></p>
</section>
<section id="interpretation" class="level4">
<h4 class="anchored" data-anchor-id="interpretation">Interpretation:</h4>
<p>The MLR model (<span class="math inline">\(R^2\)</span> = approx. 78.73%) explains slightly more variation than the SLR model (<span class="math inline">\(R^2\)</span> = approx. 77.23%).</p>
<p>The adjusted metric <span class="math inline">\(R^2\)</span> also increases from SLR’s approx. 76.47% to MLR’s approx. 77.26%.</p>
<p>Thus, adding carburetor barrels (<span class="math inline">\(x_6\)</span>) to the model provided a VERY small improvement in fit, but only a tiny amount. Engine displacement (<span class="math inline">\(x_1\)</span>) accounts for the vast majority of the predictive power.</p>
</section>
</section>
<section id="individual-predictor-significance-t-tests" class="level3">
<h3 class="anchored" data-anchor-id="individual-predictor-significance-t-tests">Individual Predictor Significance (t-tests)</h3>
<p>What the t-test does for us:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficients</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>coef_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>coefficients</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(coef_summary, <span class="at">caption =</span> <span class="st">"Regression Coefficients"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Regression Coefficients</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">32.8845508</td>
<td style="text-align: right;">1.5354079</td>
<td style="text-align: right;">21.417468</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: right;">-0.0531477</td>
<td style="text-align: right;">0.0061368</td>
<td style="text-align: right;">-8.660425</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x6</td>
<td style="text-align: right;">0.9592231</td>
<td style="text-align: right;">0.6702770</td>
<td style="text-align: right;">1.431085</td>
<td style="text-align: right;">0.1630948</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="hypotheses-alpha-0.05" class="level4">
<h4 class="anchored" data-anchor-id="hypotheses-alpha-0.05">Hypotheses, <span class="math inline">\(\alpha = 0.05\)</span> :</h4>
<p>Predictor adds no value to model given all other predictors are already included <span class="math display">\[H0: \beta_j = 0.\]</span></p>
<p>Predictor is significant. <span class="math display">\[Ha: \beta_j != 0.\]</span></p>
</section>
<section id="results-1" class="level4">
<h4 class="anchored" data-anchor-id="results-1">Results:</h4>
<p><strong>For <span class="math inline">\(x_1\)</span>:</strong> * t-test = -8.660425 * p-value = 1.549965e-09</p>
<p>Since p = 1.549965e-09 which is smaller than <span class="math inline">\(\alpha\)</span> = 0.05, we reject the null hypothesis #H_0$: <span class="math inline">\(\beta\)</span>j = 0.</p>
<p>Engine displacement makes a significant contribution to the modeleven when carburetor barrels (<span class="math inline">\(x_6\)</span>) are included. There is strongevidence that engine displacement is associated with gasoline mileage.</p>
<p><strong>For <span class="math inline">\(x_6\)</span>:</strong> * t-test = 1.431 * p-value = 1.630948e-01</p>
<p>Since p = 1.630948e-01 &gt; <span class="math inline">\(\alpha\)</span> = 0.05, we FAIL to reject <span class="math inline">\(H_0\)</span>.</p>
<p>The number of carburetor barrels does not make a statistically significant contribution to the model GIVEN that engine displacement is already included.</p>
</section>
<section id="interpretation-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-1">Interpretation:</h4>
<p>Despite the overall model being significant, only engine displacement is a significant individual predictor. Carburetor barrels appears to be redundant with the presence of engine displacement.</p>
</section>
</section>
</section>
<section id="confidence-vs.-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-vs.-prediction-intervals">Confidence vs.&nbsp;Prediction Intervals</h2>
<p>Finding a 95% CI for <span class="math inline">\(\beta_1\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% CI for x1, using confint() for accuracy and simplicity</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_1, <span class="st">"x1"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         2.5 %      97.5 %
x1 -0.06569892 -0.04059641</code></pre>
</div>
</div>
<p>100(1-<span class="math inline">\(\alpha\)</span>) is the confidence interval for regression coefficient <span class="math inline">\(\beta_j\)</span> given by:</p>
<p><span class="math inline">\(\beta_hat_j\)</span> ± t_(n-p),<span class="math inline">\(\alpha\)</span>/2 multiplied by “estimate standard error” or (ese) of <span class="math inline">\(\beta_hat_j\)</span> in our summary:</p>
<ul>
<li><span class="math inline">\(\beta_hat_j\)</span> = -0.05314767</li>
<li>ese(<span class="math inline">\(\beta_hat_j\)</span>) = 0.006136843</li>
<li>Critical value from t-distribution with df n-p = 32 - 3 = 29</li>
<li><span class="math inline">\(\alpha\)</span>/2 = 0.025 is approx. 2.045</li>
</ul>
<section id="result" class="level4">
<h4 class="anchored" data-anchor-id="result">Result:</h4>
<p>Lower Bound: -0.06569892 Upper Bound: -0.04059641</p>
</section>
<section id="interpretation-2" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-2">Interpretation:</h4>
<p>We are 95% confident that the true slope for <span class="math inline">\(x_1\)</span> lies between -0.06569957 and -0.04059643</p>
<p>Since the entire interval is negative, we are statistically certain that larger engines are associated with lower gas mileage.</p>
<p>For every 1 cubic inch increase in engine displacement, we estimate the car’s fuel efficiency will drop between 0.041 and 0.066 miles per gallon, holding the numbers of carburetors constant.</p>
</section>
<section id="t-statistics-for-predicting-gas-mileage" class="level3">
<h3 class="anchored" data-anchor-id="t-statistics-for-predicting-gas-mileage">t-statistics for predicting gas mileage</h3>
<p>t-statistics for: * <span class="math inline">\(H_0: \beta_1 = 0\)</span>, number of carburetors and engine displacement are redundant.</p>
<ul>
<li><span class="math inline">\(H_0: \beta_6 = 0\)</span>, they provide significant predictions for mileage.</li>
</ul>
<p>We want to test if a coefficient = 0, <span class="math inline">\(t_0 = (beta_hat_j)\)</span> / (ese(<span class="math inline">\(beta_hat_j\)</span>))</p>
<p>t-distribution with n-p degrees of freedom under <span class="math inline">\(H_0\)</span>.</p>
<p>We reject the <span class="math inline">\(H_0\)</span> if |<span class="math inline">\(t_0\)</span>| &gt; <span class="math inline">\(t_{(crit(n-p,\alpha / 2))}\)</span></p>
<p>Recall, for <span class="math inline">\(\alpha\)</span> = 0.05 and df = 20, the critical value is approcimately 2.045.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting coefficients table to see t-values</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>coef_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>coefficients</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>coef_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 32.88455083 1.535407938 21.417468 2.546135e-19
x1          -0.05314767 0.006136843 -8.660425 1.549965e-09
x6           0.95922305 0.670277025  1.431084 1.630948e-01</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get specific t-values for x1 and x6</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>t_beta1 <span class="ot">&lt;-</span> coef_summary[<span class="st">"x1"</span>, <span class="st">"t value"</span>] <span class="co"># [1] -8.660425</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>t_beta6 <span class="ot">&lt;-</span> coef_summary[<span class="st">"x6"</span>, <span class="st">"t value"</span>] <span class="co"># [1] 1.431084</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Or simply read from coefficients summary table</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># degrees of freedom for critical value</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>df_res <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>df[<span class="dv">2</span>]  <span class="co"># [1] 29</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># t-statistic for x1:</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"T-Statistic for x1: "</span>, t_beta1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>) <span class="co"># [1] -8.660425</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-Statistic for x1:  -8.660425 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-statistic for x6:</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"T-Statistic for x6: "</span>, t_beta6, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>) <span class="co"># [1] 1.431084</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-Statistic for x6:  1.431084 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># degrees of freedom:</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Degrees of Freedom: "</span>, df_res) <span class="co"># [1] 29</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Degrees of Freedom:  29</code></pre>
</div>
</div>
<section id="results-2" class="level4">
<h4 class="anchored" data-anchor-id="results-2">Results:</h4>
<p><strong>Displacement:</strong></p>
<p>For <span class="math inline">\(\beta_1\)</span> the t-value = |-8.660425| = 8.660425, thus, we reject <span class="math inline">\(H_0\)</span> since 8.660425 &gt; 2.045.</p>
<p>There is statistically significant evidence that engine displacement contributes to the model.</p>
<p><strong>Carburetors:</strong></p>
<p>For <span class="math inline">\(\beta_6\)</span> = |1.431084| = 1.431084, we FAIL to reject <span class="math inline">\(H_0\)</span> since 1.431084 is NOT &gt; 2.045.</p>
</section>
<section id="interpretation-3" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-3">Interpretation:</h4>
<p>There is statistically <strong>significant evidence</strong> that engine displacement contributes to the model. While there is <strong>insufficient evidence</strong> to claim thatthe number of carburetor barrels contribute significantly to the model when displacement is already included.</p>
</section>
</section>
<section id="confidence-interval-example" class="level3">
<h3 class="anchored" data-anchor-id="confidence-interval-example">Confidence Interval Example</h3>
<p>Finding a 95% Confidence Interval on the mean gasoline mileage when * <span class="math inline">\(x_1 = 275\)</span> * <span class="math inline">\(x_6 = 2\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining the new observation (mean gasoline milage when x1 = 275, x6 = 2)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>new_car <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> <span class="dv">275</span>, <span class="at">x6 =</span> <span class="dv">2</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% CI for Mean Response</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_1, <span class="at">newdata =</span> new_car, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 20.18739 18.87221 21.50257</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the coefficients table to see beta_hat values</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>coef_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="results-3" class="level4">
<h4 class="anchored" data-anchor-id="results-3">Results</h4>
<p>The point estimate is approx. 20.19 from the equation:</p>
<p><span class="math display">\[ \hat{y} = \beta_0 - \beta_1(275) + 0.96(2)\]</span></p>
<ul>
<li>Lower bound: 18.97221</li>
<li>Upper Bound: 21.50257</li>
</ul>
<p>They measure the uncertainty in the position of the regression plane (the average) at that specific point.</p>
</section>
<section id="interpretation-4" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-4">Interpretation:</h4>
<p>We are 95% confident that <strong>the true average gasoline mileage</strong> for all cars with an engine displacement of 275 cubic inches and 2 carburetor barrels lies between <strong>18.97 and 21.40</strong> Miles per Gallon (<span class="math inline">\(y\)</span>), a range of 2.43 MPG.</p>
<p>The small gap suggests that we are very sure about that the average mileage of cars with these specs, would be approx. 20.2 Miles Per Gallon, give or take 1.2 MPG.</p>
</section>
</section>
<section id="prediction-interval-example" class="level3">
<h3 class="anchored" data-anchor-id="prediction-interval-example">Prediction Interval Example</h3>
<p>Finding a 95% prediction interval for a new observation on gasoline mileage when: * <span class="math inline">\(x_1 = 275\)</span> * <span class="math inline">\(x_6 = 2\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># New car's specs</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>new_car_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> <span class="dv">275</span>, <span class="at">x6 =</span> <span class="dv">2</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 95% Prediction Interval</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_1, <span class="at">newdata =</span> new_car_data, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit     lwr      upr
1 20.18739 13.8867 26.48808</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the coefficients table to see beta_hat values</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>coef_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>coefficients</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>coef_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate  Std. Error   t value     Pr(&gt;|t|)
(Intercept) 32.88455083 1.535407938 21.417468 2.546135e-19
x1          -0.05314767 0.006136843 -8.660425 1.549965e-09
x6           0.95922305 0.670277025  1.431084 1.630948e-01</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual Standard Error</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sigma_hat <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>sigma</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>sigma_hat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.012815</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>df_res <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_1)<span class="sc">$</span>df[<span class="dv">2</span>]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>df_res</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29</code></pre>
</div>
</div>
<section id="results-4" class="level4">
<h4 class="anchored" data-anchor-id="results-4">Results:</h4>
<p><strong>point estimate: 20.18739</strong> <strong>Lower Bound: 13.8867</strong> <strong>Upper Bound: 26.48808</strong></p>
</section>
<section id="interpretation-5" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-5">Interpretation:</h4>
<p>We are 95% confident that a single specific automobile with 275 cubic inches engine displacement and 2 carburetor barrels will have a gasoline mileage <strong>between 13.89 and 26.49</strong> Miles per Gallon, a range of 12.6 MPG.</p>
<p>The large gap in the Prediction Interval compared theConfidence Interval suggests that individual cars arehighly variable. If we buy one specific car, its mileagecould plausibly be as low as 14 or as high as 26 which in itself is a large pool of unit.</p>
<p>While the model is very good at identifying the average behavior,it is <strong>not very precise at predicting individual outcomes</strong> because there is a lot of random variation, <span class="math inline">\(\epsilon\)</span>, between cars that engine size alone cannot explain.</p>
</section>
</section>
</section>
<section id="model-validation-and-out-of-sample-performance" class="level2">
<h2 class="anchored" data-anchor-id="model-validation-and-out-of-sample-performance">Model Validation and Out-Of-Sample Performance</h2>
<p><strong>Recall:</strong> <span class="math inline">\(SS_{Res}\)</span> measures the error on the data the model was trained on. The model is optimized specifically to minimize this error, “fitting” itself to the specific noise in that dataset.</p>
<p><span class="math inline">\(PRESS\)</span> measures the error on data points held out (leave-one-out cross-validation). Because the model hasn’t seen these points during fitting, it cannot overfit to them, resulting in larger errors.</p>
<p><span class="math inline">\(PRESS\)</span> residual for point <span class="math inline">\(i\)</span> is measured by <span class="math inline">\(e_i\)</span> = <span class="math inline">\(e_i\)</span> / <span class="math inline">\(1-h_ii\)</span>.</p>
<p><span class="math inline">\(e_i\)</span> being the original residual, <span class="math inline">\(h_ii\)</span> is the leverage of <span class="math inline">\(i\)</span> which is always between 0 and 1 (and typically &gt; 0).</p>
<p>Since the denominator is less than 1, the <span class="math inline">\(PRESS\)</span> residual is mathematically guaranteed to be larger in magnitude than the ordinary residual.</p>
<p>Therefore, the sum of squared <span class="math inline">\(PRESS\)</span> residuals <span class="math inline">\(PRESS\)</span> will be larger than the sum of squared ordinary residuals <span class="math inline">\(SS_{Res}\)</span></p>
<p>We want to find <span class="math inline">\(SS_T\)</span> and the out-of-sample <span class="math inline">\(R^2\)</span> using the given PRESS statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span> (model_1)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals and Leverage (hat values)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>hat_vals <span class="ot">&lt;-</span> <span class="fu">lm.influence</span>(model)<span class="sc">$</span>hat</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>hat_vals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6          7 
0.09207252 0.09207252 0.12870411 0.09014027 0.11476750 0.09859164 0.04164997 
         8          9         10         11         12         13         14 
0.04272949 0.13774133 0.12883899 0.09207252 0.14339341 0.06221419 0.13425917 
        15         16         17         18         19         20         21 
0.08454341 0.05590564 0.14027886 0.09859164 0.09207252 0.06489361 0.04164997 
        22         23         24         25         26         27         28 
0.09859405 0.08739622 0.12883899 0.08454341 0.10916816 0.09014643 0.06489361 
        29         30         31         32 
0.09014027 0.09014027 0.08947765 0.08947765 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">resid</span>(model)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># PRESS Residuals, predictively adjusted residuals</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>pressres <span class="ot">&lt;-</span> <span class="fu">resid</span>(model)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">lm.influence</span>(model)<span class="sc">$</span>hat) </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># SSRes, Residual sum of squares</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>SSRes <span class="ot">&lt;-</span> <span class="fu">sum</span>(residuals <span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co"># PRESS, Predicted Residual Error Sum of Squares</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>PRESS <span class="ot">&lt;-</span> <span class="fu">sum</span>(pressres <span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Total Sum of Squares, Sum of differences from the mean of y</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((dat<span class="sc">$</span>y <span class="sc">-</span> <span class="fu">mean</span>(dat<span class="sc">$</span>y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Out of sample $R^2$ (Prediction R-Squared)</span></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>R2_prediction <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (PRESS<span class="sc">/</span>SST)</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual Sum of Squares</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Residual Sum of Squares (SSRes): "</span>, SSRes, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Residual Sum of Squares (SSRes):  263.2345 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicted Residual Error Sum of Squares (PRESS): "</span>, PRESS, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Residual Error Sum of Squares (PRESS):  328.7654 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Total Sum of Squares (SST): "</span>, SST, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total Sum of Squares (SST):  1237.544 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Out-of-sample R-Squared (R2_prediction): "</span>, R2_prediction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-of-sample R-Squared (R2_prediction):  0.7343405</code></pre>
</div>
</div>
<section id="results-5" class="level4">
<h4 class="anchored" data-anchor-id="results-5">Results:</h4>
<ul>
<li><span class="math inline">\(R^2\)</span> of MLR: 0.7872928</li>
<li>Adjusted <span class="math inline">\(R^2\)</span> of MLR: 0.7726233</li>
<li>Out-of-sample <span class="math inline">\(R^2\)</span>: 0.7343405</li>
</ul>
</section>
<section id="interpretation-6" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-6">Interpretation:</h4>
<p>Based on the out-of-sample <span class="math inline">\(R^2\)</span>:</p>
<ul>
<li><p>Prediction <span class="math inline">\(R^2\)</span> (0.734) is very close to the Adjusted <span class="math inline">\(R^2\)</span> (0.773). This indicates that the model generalizes well and theperformance does not drop much when it faces new cars.</p></li>
<li><p>It is not suffering from severe overfitting.The model is not relying on quirks or outliers in the 32 car dataset to achieve its score.</p></li>
<li><p>We can expect this model to explain about 74% of the variation in gasoline mileage for future cars.</p></li>
</ul>
<p>If the Prediction <span class="math inline">\(R^2\)</span> were significantly lower (e.g., 0.50), it would suggest the model fits the training data well but fails to predict new, unseen observations accurately.</p>
</section>
<section id="cross-validation-optimal-model-selection" class="level3">
<h3 class="anchored" data-anchor-id="cross-validation-optimal-model-selection">Cross-Validation &amp; Optimal Model Selection</h3>
<p>We deleted half the observations (chosen at random), and refit the regression model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Split</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>dat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       y    x1 x6
1  18.90 350.0  4
2  17.00 350.0  4
3  20.00 250.0  1
4  18.25 351.0  2
5  20.07 225.0  1
6  11.20 440.0  4
7  22.12 231.0  2
8  21.47 262.0  2
9  34.70  89.7  2
10 30.40  96.9  2
11 16.50 350.0  4
12 36.50  85.3  2
13 21.50 171.0  2
14 19.70 258.0  1
15 20.30 140.0  2
16 17.80 302.0  2
17 14.39 500.0  4
18 14.89 440.0  4
19 17.80 350.0  4
20 16.41 318.0  2
21 23.54 231.0  2
22 21.47 360.0  2
23 16.59 400.0  4
24 31.90  96.9  2
25 29.40 140.0  2
26 13.27 460.0  4
27 23.90 133.6  2
28 19.73 318.0  2
29 13.90 351.0  2
30 13.27 351.0  2
31 13.77 360.0  4
32 16.50 360.0  4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>train_indexes <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n<span class="sc">/</span><span class="dv">2</span>) <span class="co"># Random 16 indexes</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> dat[train_indexes, ]</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> dat[<span class="sc">-</span>train_indexes, ]</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model on the TRAINING data only</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>model_half <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x6, <span class="at">data =</span> train_data)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="co"># model_half</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare Coefficients</span></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Full Model (n=32): "</span>, <span class="fu">coef</span>(model_1), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Full Model (n=32):  32.88455 -0.05314767 0.9592231 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Half Model (n=16): "</span>, <span class="fu">coef</span>(model_half), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Half Model (n=16):  32.18472 -0.05101269 0.824131 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Out-of-Sample $R^2$ on the </span><span class="al">TEST</span><span class="co"> data</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict y values for the test set using half-model</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_half, <span class="at">newdata =</span> test_data)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sum of Squared Errors (SSE) for the test set</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>sse_test <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_data<span class="sc">$</span>y <span class="sc">-</span> preds)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Total Sum of Squares (SST) for the test set</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>sst_test <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_data<span class="sc">$</span>y <span class="sc">-</span> <span class="fu">mean</span>(test_data<span class="sc">$</span>y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate R-Squared</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>r2_out <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (sse_test <span class="sc">/</span> sst_test)</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictive Performance</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Out-of-Sample R-Squared: "</span>, r2_out) <span class="co"># 0.8234939</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Out-of-Sample R-Squared:  0.8234939</code></pre>
</div>
</div>
<section id="interpretation-7" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-7">Interpretation:</h4>
<section id="have-the-regression-coefficients-changed-dramatically" class="level5">
<h5 class="anchored" data-anchor-id="have-the-regression-coefficients-changed-dramatically">Have the regression coefficients changed dramatically?</h5>
<p>In terms of the <span class="math inline">\(\beta_1\)</span>, <strong>Displacement</strong>: * Full Model: -0.053 * Half Model: -0.05101</p>
<p>The coefficient for <span class="math inline">\(\beta_1\)</span> remained relatively stable, indicating a robust relationship.</p>
<p>However, <strong>Carburetors</strong> (<span class="math inline">\(\beta_6\)</span>) changed noticeably from * 0.9592231 (full model) to * 0.824131 (half model), but it is still not a dramatic change.</p>
<p>This confirms that <span class="math inline">\(\beta_6\)</span> is an unstable estimator sensitive to the specific data points used.</p>
</section>
<section id="how-well-does-this-model-predict" class="level5">
<h5 class="anchored" data-anchor-id="how-well-does-this-model-predict">How well does this model predict?</h5>
<p><span class="math display">\[Out-of-Sample R-Squared = 0.8234939\]</span></p>
<p>In terms of this specific metric, the model appears to predict extremely well—better, than the model trained on the full dataset.</p>
<p>It explains 82.35% of the variance in the unseen test data. However, this high performance is likely misleading and indicates instability due to the small sample size (n = 16 for training)</p>
<p>We must consider the random 16 cars for testing, which could have lined up perfectly with the trend of the other 16 cars. We must also consider the high variance. A stable model would give consistent results, but one split can give 0.82 while another gives 0.40. Thus, the model performance is heavily dependent on exactly which cars are chose for training.</p>
<p>While the Out-of-Sample R-Squared of 0.823 suggests excellent predictive power, the fact that it exceeds the full model’s fit 0.787 implies this result is an artifact of sampling variability. The small sample size, N = 32, makes the model unstable; its performance fluctuates wildly depending on which observations are included in the training set.</p>
</section>
</section>
</section>
<section id="computing-r2-adjusted-r2-c_p-aic-and-bic-for-each-model." class="level3">
<h3 class="anchored" data-anchor-id="computing-r2-adjusted-r2-c_p-aic-and-bic-for-each-model.">Computing <span class="math inline">\(R^2\)</span>, adjusted <span class="math inline">\(R^2\)</span>, <span class="math inline">\(C_p\)</span>, AIC and BIC for each model.</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Models</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> dat)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co"># y = $\beta$0 + $\epsilon$, Intercept only</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> dat)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="co"># y = $$ \beta_0 + \beta_1x1 + \epsilon, x_1 $$ (only Displacement)</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x6, <span class="at">data =</span> dat)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="co"># y = $$\beta_0$ + \beta6 x6 + \epsilon, x_6 $$ (only Carburetors)</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x6, <span class="at">data =</span> dat)</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="co"># y = $$ \beta_0 + \beta_1 x1 + \beta_6 x6 + \epsilon$$, (Full Model)</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="co"># MSE ($\sigma^2$) from the full model for Cp calculation</span></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>mse_full <span class="ot">&lt;-</span> (<span class="fu">summary</span>(m4)<span class="sc">$</span>sigma)<span class="sc">^</span><span class="dv">2</span> </span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>mse_full</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.077053</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to calculate all metrics for a single model</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>get_metrics <span class="ot">&lt;-</span> <span class="cf">function</span>(model, full_mse) {</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat)</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(model)) <span class="co"># Number of parameters with intercept</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  rss <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">resid</span>(model)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Residual Sum of Squares</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Metrics</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  r2 <span class="ot">&lt;-</span> s<span class="sc">$</span>r.squared</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  adj_r2 <span class="ot">&lt;-</span> s<span class="sc">$</span>adj.r.squared</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  aic <span class="ot">&lt;-</span> <span class="fu">AIC</span>(model)</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  bic <span class="ot">&lt;-</span> <span class="fu">BIC</span>(model)</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Mallows' $C_p$ Formula: (RSS / MSE_full) - (n - 2*p)</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>  cp <span class="ot">&lt;-</span> (rss <span class="sc">/</span> full_mse) <span class="sc">-</span> (n <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> p)</span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">c</span>(<span class="at">p=</span>p, <span class="at">R2=</span>r2, <span class="at">Adj_R2=</span>adj_r2, <span class="at">Cp=</span>cp, <span class="at">AIC=</span>aic, <span class="at">BIC=</span>bic))</span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Results</span></span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model_1 =</span> <span class="fu">get_metrics</span>(m1, mse_full),</span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model_2 =</span> <span class="fu">get_metrics</span>(m2, mse_full),</span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model_3 =</span> <span class="fu">get_metrics</span>(m3, mse_full),</span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model_4 =</span> <span class="fu">get_metrics</span>(m4, mse_full)</span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Transpose</span></span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">t</span>(results))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        p        R2    Adj_R2         Cp      AIC      BIC
Model_1 1 0.0000000 0.0000000 106.337646 211.7768 214.7083
Model_2 2 0.7722712 0.7646803   3.048003 166.4296 170.8268
Model_3 2 0.2371662 0.2117384  76.002961 205.1139 209.5111
Model_4 3 0.7872928 0.7726233   3.000000 166.2460 172.1089</code></pre>
</div>
</div>
<section id="results-6" class="level4">
<h4 class="anchored" data-anchor-id="results-6">Results:</h4>
<p>We can first eliminate model 1 because it assumes neither engine size nor carburetors affect gas mileage. It assumes every car simply gets the average mileage, ȳ.</p>
<p><span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span> = 0, and AIC = 211.8 which is the highest score, a.k.a. the worst score.</p>
<p>We have previously proved that engine size do matter.</p>
<p>We can then eliminate model 3 because it assumes ONLY the number of carburetors matters while engine size does not.</p>
<p><span class="math inline">\(R^2\)</span> = 0.237 means that this model only explains 24% of the difference in gas mileage. Comparing 24% to Models 2 and 4’s approx. 76-77%, we can already eliminate Model 3 since it only explains approximate 24% of the difference in gas mileage. AIC is also 205.1139 which is the second highest (worst) score.</p>
<p>Now between Model 2 and 4: * In terms of <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span>, Model 4’s is slightly higher. This means that model 4, technically fits the the data better.</p>
<ul>
<li><p>Model 4’s AIC is slightly lower, which suggests that its prediction accuracy is a slightly better.</p></li>
<li><p>Model 4’s Mallow’s <span class="math inline">\(C_p\)</span> is 3.0 which is exactly p (p = 3). This is the definition of a “unbiased” model. Model 2’s Mallow’s <span class="math inline">\(C_p\)</span> = 3.048003, which is also a good fit since it’s approximate 2 and is not &lt; 2. It hits the target despite 1 less variable.</p></li>
<li><p>The most important metric revolves around BIC. BIC applies a stronger penalty for adding variables and favor the simpler model when the improvement in fit is marginal.</p></li>
</ul>
<p>The lower BIC for Model 2 confirms that the extra variable is unnecessary complexity. Recall, we confirmed the t-test for <span class="math inline">\(x_6\)</span> to be insignificant with p = 0.163 &gt; <span class="math inline">\(\alpha\)</span> (0.05). Adding it barely improves the fit.</p>
<ul>
<li>Model 2 is much simpler with only 1 predictor vs.&nbsp;having the need for 2.</li>
</ul>
<p><strong>Conclusion:</strong></p>
<p>Although Model 4 has a slightly higher Adjusted <span class="math inline">\(R^2\)</span> and lower AIC, the differences are negligible. Model 2 has the lowest BIC (170.8 vs 172.1), which penalizes complexitymore strictly.</p>
<p>Additionally, the previous t-test showed that x6 is not statistically significant.</p>
<p>Therefore, Model 2 provides the best balance of fit and simplicity, the better choice that performs just as well as Model 4, but simpler and easier to interpret.</p>
</section>
</section>
<section id="fold-cross-validation-error" class="level3">
<h3 class="anchored" data-anchor-id="fold-cross-validation-error">5-fold cross-validation error</h3>
<p>Identifying the most appropriate model, which has the smallest cross-validation error.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Shuffle the dataset randomly</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co">#    We scramble the rows so the folds are random</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>dat_shuffled <span class="ot">&lt;-</span> dat[<span class="fu">sample</span>(<span class="fu">nrow</span>(dat)), ]</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 5 "Folds" (groups)</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="co">#    This assigns a number (1, 2, 3, 4, or 5) to every row</span></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">cut</span>(<span class="fu">seq</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(dat_shuffled)), <span class="at">breaks =</span> <span class="dv">5</span>, <span class="at">labels =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a generic function to run CV on any model formula</span></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>calc_cv_error <span class="ot">&lt;-</span> <span class="cf">function</span>(formula_input) {</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>  mse_vector <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">5</span>) <span class="co"># A place to store the 5 errors</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) {</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define Test and Train for this fold</span></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a>    testIndices <span class="ot">&lt;-</span> <span class="fu">which</span>(folds <span class="sc">==</span> i, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>    testData    <span class="ot">&lt;-</span> dat_shuffled[testIndices, ]</span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a>    trainData   <span class="ot">&lt;-</span> dat_shuffled[<span class="sc">-</span>testIndices, ]</span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># fit the model using lm() on TRAINING data</span></span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a>    model <span class="ot">&lt;-</span> <span class="fu">lm</span>(formula_input, <span class="at">data =</span> trainData)</span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Predict on </span><span class="al">TEST</span><span class="co"> data</span></span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a>    preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> testData)</span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MSE for this fold: mean((Actual - Predicted)^2)</span></span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a>    mse_vector[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>((testData<span class="sc">$</span>y <span class="sc">-</span> preds)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return average of the 5 MSEs</span></span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (<span class="fu">mean</span>(mse_vector))</span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the function for all 4 models</span></span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a>cv_error_1 <span class="ot">&lt;-</span> <span class="fu">calc_cv_error</span>(y <span class="sc">~</span> <span class="dv">1</span>)          <span class="co"># Model 1</span></span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a>cv_error_2 <span class="ot">&lt;-</span> <span class="fu">calc_cv_error</span>(y <span class="sc">~</span> x1)         <span class="co"># Model 2</span></span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a>cv_error_3 <span class="ot">&lt;-</span> <span class="fu">calc_cv_error</span>(y <span class="sc">~</span> x6)         <span class="co"># Model 3</span></span>
<span id="cb64-38"><a href="#cb64-38" aria-hidden="true" tabindex="-1"></a>cv_error_4 <span class="ot">&lt;-</span> <span class="fu">calc_cv_error</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x6)    <span class="co"># Model 4</span></span>
<span id="cb64-39"><a href="#cb64-39" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CV Error Model 1:"</span>, cv_error_1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>CV Error Model 1: 40.38771 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CV Error Model 2:"</span>, cv_error_2, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>CV Error Model 2: 10.5516 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CV Error Model 3:"</span>, cv_error_3, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>CV Error Model 3: 32.77996 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"CV Error Model 4:"</span>, cv_error_4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>CV Error Model 4: 9.76937</code></pre>
</div>
</div>
<section id="results-and-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="results-and-interpretation">Results and Interpretation:</h4>
<p>In terms of the different models, we can already eliminate Model 1 and 3 due to their high error results. Simply using the average and the number of carburetors are weak predictors.</p>
<p>Based on the 5-fold cross validation, Model 4 is the selected model because it minimizes the estimated test Mean Squared Error and shows the smallest cross-validation error result.</p>
<p>This suggests that the carburetor variable, while not themost statistically significant in hypothesis testing, likely provides a very small amount of useful signal that improves prediction accuracy on unseen data just enough to outperform the simpler model.</p>
<p>Previously, we preferred Model 2 because BIC and Parsimony favored simplicity, and the difference in fit, <span class="math inline">\(R^2\)</span>, was negligible. Model 2 is better for explanation, while Model 4 is slightly better for pure prediction.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>